export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const CORRECT_ANS = 'CORRECT_ANS';
export const WRONG_ANS = 'WRONG_ANS';
export const FETCH_PAR_SCORES = 'FETCH_PAR_SCORES';
export const UPDATE_SCORE = 'UPDATE_SCORE';
