export const FETCH_LEVELS = 'FETCH_LEVELS';
export const FETCH_MODULE_NAMES = 'FETCH_MODULE_NAMES';
export const FETCH_PAR_SCORES = 'FETCH_PAR_SCORES';
export const FETCH_CURRENT_SCORES = 'FETCH_CURRENT_SCORES';
