const 
database = {
/*

this is the structure of the database

this way it's easy to query for: 
- event hosted by a specific NDI team, at a specific location (country, city...), in a specific year
- user
- users' scores at a specific event (each event contains data: host, country, city...)

also, it's easier to add more data points to a user:
gender: "female",
age_group: "20-25",

*/
    users: [
        {
            id: "1", // auto generated by database
            number: "0123456789", // phone number, identifies user
            // each user could attend several events, at each event, the user will have a new set of scores
            events: [
                {
                    eventID: "1", // linked to events collection
                    scores: [
                        {level1: "100%"},
                        {level2: "90%"},
                        {level3: "80%"}
                    ]
                }
                // other events
                // ...
            ]
        }
        // other users
        // ...
    ],
    events: [
        {
            // each event is hosted by an NDI team, at one country, one city, one year
            id: "1",
            host: "LAC", 
            country: "Guatemala",
            city: "City 1",
            year: "2018"
        }
        // other events
        // ...
    ]
}