const
database = {
    // In use:
    questions: [
        {
            question: "the actual question. e.g: what is the right answer?",
            option1: "option 1 or answer 1",
            option2: "answer 2",
            option3: "answer 3",
            option4: "answer 4",
            answer: "1", // string, the right option for the question 
            type: "matching",
            language: "Spanish",
            tags: [] // not in use
        },
        {
            // another question
        }
    ]
/*
this is the structure of the database
this way it's easy to query for:
- event hosted by a specific NDI team, at a specific location (country, city...), in a specific year
- user
- users' scores at a specific event (each event contains data: host, country, city...)
also, it's easier to add more data points to a user:
gender: "female",
age_group: "20-25",
*/
    users: [
        {
            id: "1", // auto generated by database
            number: "0123456789", // phone number, identifies user
            // each user could attend several events, at each event, the user will have a new set of scores
            events: [
                {
                    eventID: "1", // linked to events collection
                    game: 1,
                    scores: [
                        {level1: "100%"},
                        {level2: "90%"},
                        {level3: "80%"}
                    ]
                },
                // ... more events
            ]
        }
        // ... more users
    ],
    events: [
        {
            // each event is hosted by an NDI team, at one country, one city, one year
            id: "1",
            host: "LAC",
            country: "Guatemala",
            city: "City 1",
            year: "2018"
        }
        // ... more events
    ],
    admin: [
        {
            id: "1",
            name: "NDI-CEE",
            pin: "1234" // short and easy to login
        }
        // ... more admins
    ],
    questions: [
        {
            id: "1",
            type:"mutliplechoice",
            question:"what are fruitloops",
            answers: ["cereal", "mile"],
            answer:"cereal",
            language: "spanish",
            tags: ["latinamerica", "caribbean", "guatemala"]
        }
    ],
    games: [
        {
            id: "1",
            questions: [1, 5, 10, 20, 50]
        }
    ]
}




